data:
  train_path: "data/raw/train.csv"
  test_path: "data/raw/test.csv"
  output_path: "data/processed"
preprocessing:
  input_path: "data/processed/train_data.csv"
  test_path: "data/processed/test_data.csv"
  output_path: "data/interim"

